# Generated by Django 4.2.2 on 2023-07-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_myorders"),
    ]

    operations = [
        migrations.AddField(
            model_name="myorders",
            name="pending",
            field=models.BooleanField(default=False),
        ),
    ]
